# -*- Mode: Makefile; -*-
#
# See COPYRIGHT in top-level directory.
#

CC=mpicc
CFLAGS= -fopenmp -g -I../common
STENCIL_COMMON_SRC=../common/stencil/printarr_par.c ../common/perf_stat.c
STENCIL_CFLAGS=$(CFLAGS) -I../common/stencil
BINS=stencil

all: $(BINS)

stencil: stencil_omp.c $(STENCIL_COMMON_SRC)
	$(CC) $(STENCIL_CFLAGS) $^ -o $@ -lm

clean:
	rm -f $(BINS)
	rm -f output*.bmp
