# -*- Mode: Makefile; -*-
#
# See COPYRIGHT in top-level directory.
#

NVCC=nvcc
NVCFLAGS=-I../common/stencil -I$(MPI_INSTALL_PATH)/include -O2 -g
NVLDFLAGS=-lcuda -lcudart -L$(MPI_INSTALL_PATH)/lib -lmpi
BINS=stencil_cuda

all: $(BINS)

stencil_cuda: stencil_cuda.cu
	$(NVCC) $(NVCFLAGS) $^ -o $@ -lm $(NVLDFLAGS)

clean:
	rm -f $(BINS)
